name: chaos ensemble
favicon: null
layout_spectrum: 0
typography_spectrum: 0.69351
title: chaos ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#000000'
    - '#656565'
    - '#424242'
    - '#bababa'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
