name: chaos ensemble
favicon: null
layout_spectrum: 0.95499
typography_spectrum: 0.60498
title: chaos ensemble
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#eec899'
    - '#4d3449'
    - '#bd8574'
    - '#feeab5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
